---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maonoglo/repositories/razormarkets  # Replace with the actual path to your website's root directory
    - /usr/local/cpanel/3rdparty/bin/git pull origin main  # Replace 'main' with your main branch name if different